// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1cbwY6dKYjPXSdouD16475TOkRpFYIn0',
    appId: '1:514235033431:android:01ce899df896a8ebd28012',
    messagingSenderId: '514235033431',
    projectId: 'qcrack-auth',
    storageBucket: 'qcrack-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNTz_aXSWuPLTgbx8nsdGBqsHxcFUUTfY',
    appId: '1:514235033431:ios:bd8d1cfb42bc2745d28012',
    messagingSenderId: '514235033431',
    projectId: 'qcrack-auth',
    storageBucket: 'qcrack-auth.appspot.com',
    androidClientId: '514235033431-ck9k1191a8krs4nru890jt0g25uf7kk4.apps.googleusercontent.com',
    iosClientId: '514235033431-2cocjp77602aotm13iki5qfoelj5c5c7.apps.googleusercontent.com',
    iosBundleId: 'io.quind.qcracks',
  );
}
